site_name: Holochain Docs

# Repository
repo_url: https://github.com/holochain/docs-pages

# Navigation
nav:
  - Get Started:
    - Introduction: index.md
    - Why Holochain?: why-holochain.md
    - Who is Holochain For?: who-is-holochain-for.md
    - What is Holochain?: what-is-holochain.md
    - Install Holochain: install.md
    - Get Involved: get-involved.md
    - Glossary: glossary.md
    - Advanced Installation Tips: install-advanced.md
  - Core Concepts:
    - Introduction: 'concepts/index.md'
    - The Basics: 'concepts/1_the_basics.md'
    - Application Architecture: 'concepts/2_application_architecture.md'
    - Source Chain: 'concepts/3_source_chain.md'
    - DHT: 'concepts/4_dht.md'
    - Links and Anchors: 'concepts/5_links_anchors.md'
    - CRUD Actions: 'concepts/6_crud_actions.md'
    - Validation: 'concepts/7_validation.md'
    - Calls and Capabilities: 'concepts/8_calls_capabilities.md'
    - Signals: 'concepts/9_signals.md'
  - Resources:
    - Introduction: 'resources/index.md'
    - DNA Build Tutorial: 'https://github.com/holochain/holochain/blob/develop/docs/build_tutorial.md'
    - Dependency Pinning Guide: 'resources/dependency-pinning-guide.md'
    - Install NixOS on External HDD: 'resources/install-nixos-on-external-hdd.md'
    - Holochain RSM Migration Guide: 'https://holochain-open-dev.github.io/blog/holochain-rsm-migration-guide/'
  - References:
    - Introduction: 'references.md'
    - HDK: 'https://docs.rs/hdk/0.0.100/hdk/'
    - HDK introductory guide: 'https://github.com/holochain/holochain/blob/develop/crates/hdk/README.md'
    - Admin API: '/rustdoc/holochain_conductor_api/enum.AdminRequest.html'
    - App API: '/rustdoc/holochain_conductor_api/enum.AppRequest.html'


# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  feature:
    tabs: true
  font:
    text: 'Work Sans'
    code: 'Roboto Mono'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  favicon: 'https://forum.holochain.org/uploads/default/original/1X/79f6577e3c8102e1f0caf8d2f43d4fcf472a3e34.png'

extra_css:
  - 'custom/style.css'
  - 'custom/prism.css'

extra_javascript:
  - 'custom/prism.js'

google_analytics:
  - 'UA-131226536-4'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - smarty
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.betterem
