site_name: Holochain Docs

# Repository
repo_url: https://github.com/holochain/docs-pages

# Navigation
nav:
  - Get Started:
    - Introduction: index.md
    - Why Holochain?: why-holochain.md
    - Who is Holochain For?: who-is-holochain-for.md
    - What is Holochain?: what-is-holochain.md
    - Install Holochain: install.md
    - Create a New App: create-new-app.md
    - Get Involved: get-involved.md
    - Glossary: glossary.md
  - Core Concepts:
    - Introduction: 'concepts/index.md'
    - The Basics: 'concepts/1_the_basics.md'
    - Application Architecture: 'concepts/2_application_architecture.md'
    - Source Chain: 'concepts/3_private_data.md'
    - DHT: 'concepts/4_public_data_on_the_dht.md'
    - Links: 'concepts/5_linking_data_together.md'
    - CRUD Operations: 'concepts/6_modifying_and_deleting_data.md'
    - Validation: 'concepts/7_validation.md'
    - Node-to-Node Messaging: 'concepts/8_node_to_node_messaging.md'
  - Resources:
    - Introduction: 'resources/index.md'
    - Community Contributions:
      - Holochain RSM Migration Guide: 'https://holochain-open-dev.github.io/blog/holochain-rsm-migration-guide/'
      - Install NixOS on External HDD: 'resources/install-nixos-on-external-hdd.md'
  - API:
    - API: 'https://docs.rs/hdk'


# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  feature:
    tabs: true
  font:
    text: 'Work Sans'
    code: 'Roboto Mono'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  favicon: 'https://forum.holochain.org/uploads/default/original/1X/79f6577e3c8102e1f0caf8d2f43d4fcf472a3e34.png'

extra_css:
  - 'custom/style.css'
  - 'custom/prism.css'

extra_javascript:
  - 'custom/prism.js'

google_analytics:
  - 'UA-131226536-4'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - smarty
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.betterem
